window.TrackForge=window.TrackForge||{};(()=>{const T=window.TrackForge,$=s=>document.querySelector(s),canvas=$('#editorCanvas'),ctx=canvas.getContext('2d');T.points=[];T.connections=[];T.closed=false;T.zoom=1;T.connectMode=false;T.connectFrom=-1;let drag=-1;
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);T.draw();if(T.onResize)T.onResize()}new ResizeObserver(resize).observe(canvas);
T.edges=()=>{const a=T.points.slice(0,-1).map((_,i)=>[i,i+1]);T.connections.forEach(e=>{if(e[0]!==e[1]&&!a.some(x=>x[0]===e[0]&&x[1]===e[1]))a.push(e)});if(T.closed&&T.points.length>2&&!a.some(e=>e[0]===T.points.length-1&&e[1]===0))a.push([T.points.length-1,0]);return a};
T.route=()=>{const adj=T.points.map(()=>[]);T.edges().forEach(([a,b])=>{if(adj[a])adj[a].push(b)});let out=[],seen=new Set(),cur=0;while(cur!=null&&!seen.has(cur)&&out.length<=T.points.length+1){seen.add(cur);out.push(cur);cur=adj[cur]?.find(x=>!seen.has(x))}return out.length>2?out:T.points.map((_,i)=>i)};
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-canvas.clientWidth/2)/T.zoom+canvas.clientWidth/2,y:(e.clientY-r.top-canvas.clientHeight/2)/T.zoom+canvas.clientHeight/2}}function nearest(x,y){let n=-1,b=20/T.zoom;T.points.forEach((p,i)=>{const d=Math.hypot(p.x-x,p.y-y);if(d<b){n=i;b=d}});return n}
function line(a,b){if(!T.points[a]||!T.points[b])return;ctx.moveTo(T.points[a].x,T.points[a].y);ctx.lineTo(T.points[b].x,T.points[b].y)}
T.draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(T.zoom,T.zoom);ctx.translate(-w/2,-h/2);if($('#gridToggle').checked){ctx.strokeStyle='#20304b';ctx.lineWidth=1/T.zoom;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}const es=T.edges();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#91a4c7';ctx.lineWidth=(+$('#widthRange').value*8+14)/T.zoom;ctx.beginPath();es.forEach(e=>line(...e));ctx.stroke();ctx.strokeStyle='#27334c';ctx.lineWidth=+$('#widthRange').value*8/T.zoom;ctx.beginPath();es.forEach(e=>line(...e));ctx.stroke();ctx.strokeStyle='#dbeafe55';ctx.lineWidth=2/T.zoom;ctx.beginPath();es.forEach(e=>line(...e));ctx.stroke();T.points.forEach((p,i)=>{ctx.beginPath();ctx.fillStyle=i===T.connectFrom?'#facc15':i===0?'#67e8f9':'#fb7185';ctx.arc(p.x,p.y,(i===T.connectFrom?9:6)/T.zoom,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=10/T.zoom+'px sans-serif';ctx.fillText(i+1,p.x+9/T.zoom,p.y-8/T.zoom)});ctx.restore()};
canvas.addEventListener('pointerdown',e=>{const p=pos(e),n=nearest(p.x,p.y);if(T.connectMode){if(n<0)return;if(T.connectFrom<0)T.connectFrom=n;else if(n!==T.connectFrom){if(!T.connections.some(x=>x[0]===T.connectFrom&&x[1]===n))T.connections.push([T.connectFrom,n]);T.connectFrom=-1;T.draw();T.update?.()}return}if(n>=0){drag=n;canvas.setPointerCapture(e.pointerId)}else if(!T.closed){T.points.push(p);T.draw();T.update?.()}});canvas.addEventListener('pointermove',e=>{if(drag<0)return;T.points[drag]=pos(e);T.draw();T.update?.()});canvas.addEventListener('pointerup',()=>drag=-1);canvas.addEventListener('dblclick',()=>{if(T.points.length>2){T.closed=true;T.draw();T.update?.()}});canvas.addEventListener('wheel',e=>{e.preventDefault();T.zoom=Math.max(.5,Math.min(2.8,T.zoom+(e.deltaY<0?.1:-.1)));T.draw()},{passive:false});
T.template=type=>{const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2;let a=[];if(type==='oval')for(let i=0;i<18;i++){const q=i*Math.PI*2/18;a.push({x:cx+Math.cos(q)*w*.35,y:cy+Math.sin(q)*h*.29})}else{const raw=type==='f1'?[[-.4,-.22],[-.2,-.34],[.1,-.3],[.38,-.14],[.38,.02],[.2,.13],[.34,.3],[.03,.33],[-.07,.1],[-.32,.3],[-.42,.12],[-.28,-.02]]:[[-.4,-.2],[-.16,-.33],[.13,-.29],[.35,-.12],[.28,.05],[.04,.02],[.25,.3],[-.04,.33],[-.3,.2],[-.4,.02]];a=raw.map(([x,y])=>({x:cx+x*w,y:cy+y*h}))}T.points=a;T.connections=[];T.closed=true;T.draw();T.update?.()};T.resize=resize;})();
